name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
        
    steps:
    - uses: docker/build-push-action@v5.3.0
      with:
        #build-args: # optional
        #build-contexts: src
        #cache-from: type=gha
        #cache-to: type=gha,mode=max
        # context: src
        push: true # optional, default is false
